require('dotenv').config();
const MINIMUM_BONDS_PROFITABILITY = Number(process.env.MINIMUM_BONDS_PROFITABILITY);
exports.MINIMUM_BONDS_PROFITABILITY = MINIMUM_BONDS_PROFITABILITY;
const MIN_USD_PRICE_TO_SELL = Number(process.env.MIN_USD_PRICE_TO_SELL);
exports.MIN_USD_PRICE_TO_SELL = MIN_USD_PRICE_TO_SELL;
